spring:
  application:
    name: video
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html